# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2285e1921c231956a648fd397acfd288bf9034a4fd6329411705e835e32a9b7f8ccec16628b71c0897b518b01b779c7c09291c95135b6fa2b5c646f727fc5aa6

test:
  secret_key_base: a05a0316c24b9a0633002f092693bc31c09bf4087c20d40c16948d46f7145603c39a669eb1bb07aeaeff11440797177ba725754fe3f04c24f81ef87e1a62c494

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9908948c75d73438b74eca9e17af0a0b6a3b593ff09bd4c89d7c36b790712d8a3af588730a955ccccf00db41a5884353f38c00ed70ad9ea68259df347a1a0312

 # <%= ENV["SECRET_KEY_BASE"] %>
